name: EmuSC CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  release:
    types: [created]
    tags: ['v*'] # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:
    strategy:
      matrix:
       include:
        - { os: windows-latest, cc: g++, shell: 'msys2 {0}', bin: 'win32'}
        - { os: ubuntu-latest, cc: g++-10, shell: bash, bin: 'linux'}
        - { os: macos-latest, cc: g++, shell: bash, bin: 'macOS'}
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: ${{matrix.shell}}
    steps:
    - if: ${{runner.os == 'macOS'}}
      name: Install macOS Dependencies 
      run: brew install autoconf automake libtool
    - if: ${{runner.os == 'Linux'}}
      name: Install Linux Dependencies 
      run: sudo apt-get install -y libasound2-dev
    - if: ${{runner.os == 'Windows'}}
      name: Install Windows Dependencies 
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: mingw-w64-x86_64-gcc make autotools
    - name: Checkout Repo  
      uses: actions/checkout@v2
    - name: Run Autotools
      run: ./autogen.sh
    - if: ${{runner.os == 'macOS'}}
      name: Run Configure (macOS)
      run: ./configure CXXFLAGS='-std=c++11'
    - if: ${{runner.os == 'Linux'}}
      name: Run Configure (Linux)
      run: ./configure CXXFLAGS='-pthread'
    - if: ${{runner.os == 'Windows'}}
      name: Run Configure (Windows)
      run: ./configure
    - name: Compile Code
      run: make CXX=${{matrix.cc}}
    - if: ${{runner.os == 'macOS'}}
      name: Rename macOS Binary
      run: mv src/emusc src/emusc-${{matrix.bin}}
    - if: ${{runner.os == 'Linux'}}
      name: Rename Linux Binary
      run: mv src/emusc src/emusc-${{matrix.bin}}
    - if: ${{runner.os == 'Windows'}}
      name: Rename Windows Binary
      run: mv src/emusc.exe src/emusc-${{matrix.bin}}.exe
    - name: Upload All Binaries
      uses: actions/upload-artifact@v2
      with:
        name: build-${{runner.os}}
        path: |
          src/emusc-${{matrix.bin}}*
          
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Tag
        id: get_tag
        run: echo ::set-output name=BUILD_TAG::build-$(date +'%Y%m%d%H%M')
      - name: Get macOS Binary
        uses: actions/download-artifact@v2
        with:
          name: build-macOS
          path: build-macOS
      - name: Get Linux Binary
        uses: actions/download-artifact@v2
        with:
          name: build-Linux
          path: build-Linux
      - name: Get Windows Binary
        uses: actions/download-artifact@v2
        with:
          name: build-Windows
          path: build-Windows
      - if: github.event_name == 'push' # snapshot builds
        name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.get_tag.outputs.BUILD_TAG }}
          tag_name: ${{ steps.get_tag.outputs.BUILD_TAG }}
          prerelease: true
          files: |
            build-macOS/*
            build-Linux/*
            build-Windows/*
      - if: github.event_name == 'release' # release versioned builds
        name: Get Existing Release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: build-Windows/emusc-win32.exe
          asset_name: emusc-win32.exe
          asset_content_type: application/octet-stream
