name: EmuSC CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
       include:
        - { os: windows-latest, cc: g++ , shell: 'msys2 {0}'}
        - { os: ubuntu-latest, cc: g++ , shell: bash}
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: ${{matrix.shell}}
    steps:
    - uses: actions/checkout@v2
    - if: ${{matrix.os == 'windows-latest'}}
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: mingw-w64-x86_64-gcc make autotools
    - run: ./autogen.sh
    - run: ./configure
    - run: make CXX=${{matrix.cc}}
